# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c02ba63fcea47cf7c64091fa63179d885b2519dfd2855c8fa3a52a3810521daec863502c91e40b0507f293e57c391fb429e5602defb90b3f806b99260d1c171

test:
  secret_key_base: 2911e39a2f43dcc57c029e584208e72440b148ae703f7d8790908cdca24cb494e19a1e3fda5cfae38e01bb7886606244b62edcaed24f8a60d81b0d0d207c9dc3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
